"""Added technician, pharmacy, hospital_id, and pending_user relationships

Revision ID: 8071a6ec50c7
Revises: 7f1f6ba5cb0e
Create Date: 2025-10-30 20:17:29.649934

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8071a6ec50c7'
down_revision = '7f1f6ba5cb0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pharmacies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hospital_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'hospitals', ['hospital_id'], ['id'])

    with op.batch_alter_table('technicians', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hospital_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'hospitals', ['hospital_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technicians', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('hospital_id')

    with op.batch_alter_table('pharmacies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('hospital_id')

    # ### end Alembic commands ###
