"""Add agreement_signed to Hospital

Revision ID: f44ce1023210
Revises: f590f740549a
Create Date: 2025-10-26 23:40:17.404568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f44ce1023210'
down_revision = 'f590f740549a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agreement_signed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hospitals', schema=None) as batch_op:
        batch_op.drop_column('agreement_signed')

    # ### end Alembic commands ###
