from .users import * 
from .patient import *
from .doctor import *
from .hospital import *
from .Pharmacy import *
from .medicalrecord import *
from .Appointment import *
from .prescriptions import *
from .reviews import *
from .access import *
from .notification import *
from .pendingUser import *
from .technician import *